In [5]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

x = np.arange(10).reshape(-1, 1)
y = np.array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1])
model = LogisticRegression(solver='liblinear', random_state=0)
model.fit(x, y)

print("Classes:", model.classes_)
print("Intercept:", model.intercept_)
print("Coefficients:", model.coef_)
print("Predicted probabilities:\n", model.predict_proba(x))
print("Predictions:", model.predict(x))
print("Model score:", model.score(x, y))
print("Confusion matrix:\n", confusion_matrix(y, model.predict(x)))
print("Classification report:\n", classification_report(y, model.predict(x)))
model = LogisticRegression(solver='liblinear', C=10.0, random_state=0)
model.fit(x, y)
print("Classes:", model.classes_)
print("Intercept:", model.intercept_)
print("Coefficients:", model.coef_)
print("Predicted probabilities:\n", model.predict_proba(x))
print("Predictions:", model.predict(x))
print("Model score:", model.score(x, y))
print("Confusion matrix:\n", confusion_matrix(y, model.predict(x)))
print("Classification report:\n", classification_report(y, model.predict(x)))


Classes: [0 1]
Intercept: [-1.04608067]
Coefficients: [[0.51491375]]
Predicted probabilities:
 [[0.74002157 0.25997843]
 [0.62975524 0.37024476]
 [0.5040632  0.4959368 ]
 [0.37785549 0.62214451]
 [0.26628093 0.73371907]
 [0.17821501 0.82178499]
 [0.11472079 0.88527921]
 [0.07186982 0.92813018]
 [0.04422513 0.95577487]
 [0.02690569 0.97309431]]
Predictions: [0 0 0 1 1 1 1 1 1 1]
Model score: 0.9
Confusion matrix:
 [[3 1]
 [0 6]]
Classification report:
               precision    recall  f1-score   support

           0       1.00      0.75      0.86         4
           1       0.86      1.00      0.92         6

    accuracy                           0.90        10
   macro avg       0.93      0.88      0.89        10
weighted avg       0.91      0.90      0.90        10

Classes: [0 1]
Intercept: [-3.51335372]
Coefficients: [[1.12066084]]
Predicted probabilities:
 [[0.97106534 0.02893466]
 [0.9162684  0.0837316 ]
 [0.7810904  0.2189096 ]
 [0.53777071 0.46222929]
 [0.27502212 0.7249778

In [19]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Load or create your dataset
# For simplicity, let's create a sample dataset
data = {
    'Age': [25, 30, 35, 40, 45, 50, 55, 60, 65, 70],
    'Smoker': [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
    'Outcome': [0, 0, 0, 1, 1, 1, 1, 1, 1, 1]
}
df = pd.DataFrame(data)

# Split the dataset into features (X) and target variable (y)
X = df[['Age', 'Smoker']]
y = df['Outcome']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train a logistic regression model
model = LogisticRegression()
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Calculate the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.2f}')

# Calculate odds ratio for each feature
odds_ratio = np.exp(model.coef_)
print(f'Odds Ratio: {odds_random}')


Accuracy: 1.00


NameError: name 'odds_random' is not defined