In [13]:
import pandas as pd

In [27]:
data=pd.read_excel(r"C:\Users\Admin\Downloads\Financial Sample.xlsx")
data

Segment                   Country    Product Discount Band  \
0          Government                    Canada  Carretera           NaN   
1          Government                   Germany  Carretera           NaN   
2           Midmarket                    France  Carretera           NaN   
3           Midmarket                   Germany  Carretera           NaN   
4           Midmarket                    Mexico  Carretera           NaN   
..                ...                       ...        ...           ...   
695    Small Business                    France   Amarilla          High   
696    Small Business                    Mexico   Amarilla          High   
697        Government                    Mexico    Montana          High   
698        Government                    Canada      Paseo          High   
699  Channel Partners  United States of America        VTT          High   

     Units Sold  Manufacturing Price  Sale Price  Gross Sales  Discounts  \
0        1618.5                    3          20      32370.0       0.00   
1        1321.0                    3          20      26420.0       0.00   
2        2178.0                    3          15      32670.0       0.00   
3         888.0                    3          15      13320.0       0.00   
4        2470.0                    3          15      37050.0       0.00   
..          ...                  ...         ...          ...        ...   
695      2475.0                  260         300     742500.0  111375.00   
696       546.0                  260         300     163800.0   24570.00   
697      1368.0                    5           7       9576.0    1436.40   
698       723.0                   10           7       5061.0     759.15   
699      1806.0                  250          12      21672.0    3250.80   

         Sales      COGS    Profit       Date  Month Number Month Name  Year  
0     32370.00   16185.0  16185.00 2014-01-01             1    January  2014  
1     26420.00   13210.0  13210.00 2014-01-01             1    January  2014  
2     32670.00   21780.0  10890.00 2014-06-01             6       June  2014  
3     13320.00    8880.0   4440.00 2014-06-01             6       June  2014  
4     37050.00   24700.0  12350.00 2014-06-01             6       June  2014  
..         ...       ...       ...        ...           ...        ...   ...  
695  631125.00  618750.0  12375.00 2014-03-01             3      March  2014  
696  139230.00  136500.0   2730.00 2014-10-01            10    October  2014  
697    8139.60    6840.0   1299.60 2014-02-01             2   February  2014  
698    4301.85    3615.0    686.85 2014-04-01             4      April  2014  
699   18421.20    5418.0  13003.20 2014-05-01             5        May  2014  

[700 rows x 16 columns]

In [29]:
data.tail(666)

Segment                   Country   Product Discount Band  \
34         Government                   Germany      Velo           NaN   
35   Channel Partners                   Germany      Velo           NaN   
36         Enterprise  United States of America      Velo           NaN   
37         Enterprise                    Canada      Velo           NaN   
38     Small Business                    Canada       VTT           NaN   
..                ...                       ...       ...           ...   
695    Small Business                    France  Amarilla          High   
696    Small Business                    Mexico  Amarilla          High   
697        Government                    Mexico   Montana          High   
698        Government                    Canada     Paseo          High   
699  Channel Partners  United States of America       VTT          High   

     Units Sold  Manufacturing Price  Sale Price  Gross Sales  Discounts  \
34       1006.0                  120         350     352100.0       0.00   
35       1545.0                  120          12      18540.0       0.00   
36       2821.0                  120         125     352625.0       0.00   
37        345.0                  120         125      43125.0       0.00   
38       2001.0                  250         300     600300.0       0.00   
..          ...                  ...         ...          ...        ...   
695      2475.0                  260         300     742500.0  111375.00   
696       546.0                  260         300     163800.0   24570.00   
697      1368.0                    5           7       9576.0    1436.40   
698       723.0                   10           7       5061.0     759.15   
699      1806.0                  250          12      21672.0    3250.80   

         Sales      COGS     Profit       Date  Month Number Month Name  Year  
34   352100.00  261560.0   90540.00 2014-06-01             6       June  2014  
35    18540.00    4635.0   13905.00 2014-06-01             6       June  2014  
36   352625.00  338520.0   14105.00 2014-08-01             8     August  2014  
37    43125.00   41400.0    1725.00 2013-10-01            10    October  2013  
38   600300.00  500250.0  100050.00 2014-02-01             2   February  2014  
..         ...       ...        ...        ...           ...        ...   ...  
695  631125.00  618750.0   12375.00 2014-03-01             3      March  2014  
696  139230.00  136500.0    2730.00 2014-10-01            10    October  2014  
697    8139.60    6840.0    1299.60 2014-02-01             2   February  2014  
698    4301.85    3615.0     686.85 2014-04-01             4      April  2014  
699   18421.20    5418.0   13003.20 2014-05-01             5        May  2014  

[666 rows x 16 columns]

In [31]:
data.head(77)

Segment                   Country    Product Discount Band  \
0       Government                    Canada  Carretera           NaN   
1       Government                   Germany  Carretera           NaN   
2        Midmarket                    France  Carretera           NaN   
3        Midmarket                   Germany  Carretera           NaN   
4        Midmarket                    Mexico  Carretera           NaN   
..             ...                       ...        ...           ...   
72  Small Business  United States of America    Montana           Low   
73      Enterprise  United States of America    Montana           Low   
74       Midmarket  United States of America      Paseo           Low   
75      Government  United States of America      Paseo           Low   
76      Enterprise  United States of America      Paseo           Low   

    Units Sold  Manufacturing Price  Sale Price  Gross Sales  Discounts  \
0       1618.5                    3          20      32370.0      0.000   
1       1321.0                    3          20      26420.0      0.000   
2       2178.0                    3          15      32670.0      0.000   
3        888.0                    3          15      13320.0      0.000   
4       2470.0                    3          15      37050.0      0.000   
..         ...                  ...         ...          ...        ...   
72      2498.0                    5         300     749400.0   7494.000   
73       663.0                    5         125      82875.0    828.750   
74      1514.0                   10          15      22710.0    227.100   
75      4492.5                   10           7      31447.5    314.475   
76       727.0                   10         125      90875.0    908.750   

         Sales      COGS      Profit       Date  Month Number Month Name  Year  
0    32370.000   16185.0   16185.000 2014-01-01             1    January  2014  
1    26420.000   13210.0   13210.000 2014-01-01             1    January  2014  
2    32670.000   21780.0   10890.000 2014-06-01             6       June  2014  
3    13320.000    8880.0    4440.000 2014-06-01             6       June  2014  
4    37050.000   24700.0   12350.000 2014-06-01             6       June  2014  
..         ...       ...         ...        ...           ...        ...   ...  
72  741906.000  624500.0  117406.000 2013-09-01             9  September  2013  
73   82046.250   79560.0    2486.250 2013-10-01            10    October  2013  
74   22482.900   15140.0    7342.900 2014-02-01             2   February  2014  
75   31133.025   22462.5    8670.525 2014-04-01             4      April  2014  
76   89966.250   87240.0    2726.250 2014-06-01             6       June  2014  

[77 rows x 16 columns]

In [36]:
import os
os.getcwd()

'C:\\Users\\Admin'

In [50]:
import numpy as np

In [54]:
a=np.zeros(4)
a

array([0., 0., 0., 0.])

In [56]:
type(a)

numpy.ndarray

In [58]:
type(a[0])

numpy.float64

In [62]:
z=np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [64]:
z.shape=(10,1)
z

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [70]:
z=np.ones(10)
type(z[0])
z

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [72]:
z=np.empty(3)
z

array([7.90505033e-323, 3.95252517e-323, 5.89002372e-310])

In [78]:
z=np.linspace(2,10,5)
z

array([ 2.,  4.,  6.,  8., 10.])

In [83]:
z=np.array([10,20])
z

array([10, 20])